### PR TITLE
upgrade babel-plugin-espower to 1.0.0

### PR DESCRIPTION
**Pull request by twada**
- upgrade babel-plugin-espower to 1.0.0
- update URLs since transferred to org

### CODE REVIEW

**Comment by twada** [comment]
oops, some tests are failing? /cc @azu

**Comment by azu** [comment]
@twada
I think that this failed test caused by `shouldIgnoreByBabel` problem.
- https://github.com/power-assert-js/espower-babel/blob/54d009089abf7889f40aa2f80cb0c14f0bde57b9/lib/babelrc-util.js#L37-L39

``` js
function shouldIgnoreByBabel(filename, babelrc) {
    if (!babelrc.ignore && !babelrc.only) {
        return /node_modules/.test(filename);
    } else {
        var ignore = util.arrayify(babelrc.ignore, util.regexify);
        var only = util.arrayify(babelrc.only, util.regexify);
        return util.shouldIgnore(filename, ignore, only);
    }
}
```

`util.arrayify` always return array `[]`.

As a result, 

``` js
assert(! shouldIgnoreByBabel("only/a.js", {
                    ignore: ["lib/*.js"]
                }));
```

The above test case called like `util.shouldIgnore(filename, [ignoreRegexpPattern], []);`

``` js
export function shouldIgnore(filename: string, ignore: Array, only): boolean {
  filename = slash(filename);

  if (only) { // => unhappiness this is `true`
    for (let pattern of (only: Array)) {
      if (_shouldIgnore(pattern, filename)) return false;
    }
    return true;
  } else if (ignore.length) {// we want to get here!
    for (let pattern of (ignore: Array)) {
      if (_shouldIgnore(pattern, filename)) return true;
    }
  }

  return false;
}
```

https://github.com/babel/babel/blob/e2b39084a4a48c48ff3441aab35b22d9efc3c8d6/packages/babel/src/util.js#L114

### Conclusion

This patch fixes the failed test. 

``` diff
diff --git a/lib/babelrc-util.js b/lib/babelrc-util.js
index fc6ba42..ffb1871 100644
--- a/lib/babelrc-util.js
+++ b/lib/babelrc-util.js
@@ -34,8 +34,8 @@ function shouldIgnoreByBabel(filename, babelrc) {
     if (!babelrc.ignore && !babelrc.only) {
         return /node_modules/.test(filename);
     } else {
-        var ignore = util.arrayify(babelrc.ignore, util.regexify);
-        var only = util.arrayify(babelrc.only, util.regexify);
+        var ignore = babelrc.ignore ? util.arrayify(babelrc.ignore, util.regexify) : null;
+        var only = babelrc.only ? util.arrayify(babelrc.only, util.regexify) : null;
         return util.shouldIgnore(filename, ignore, only);
     }
 }
```

Right?

**Comment by twada** [comment]
@azu Thanks! I'll apply it.

**Comment by twada** [comment]
Now fixed! Thanks @azu!

**Comment by azu** [comment]
Release espower-babel@3.3.0

**Comment by azu** [comment]
@twada Thanks!

**Comment by twada** [comment]
@azu What a quick release under DDoS :grin:
Thanks! :tada:

**Pull request merged**
