### PR TITLE
6to5 to babel

### PR DESCRIPTION
**Pull request by azu**
- [x] use babel
- [x] rename repogitory 
- [x] rename npm package - How do?
- `npm deprecate espower-6to5@">= 1.0.0" "espower-6to5 is now espower-babel : https://github.com/azu/espower-babel/ "`
- `npm publish espower-babel`
- chore travis

https://github.com/babel/babel/issues/780

### CODE REVIEW

**Comment by azu** [comment]
future information: The project owner should prepare the guideline how to change library name, because avoid more confusion.

**Comment by twada** [comment]
:+1:

**Comment by azu** [comment]
@sebmck "espower-6to5" is now "espower-babel"! :heavy_check_mark:

**Comment by sebmck** [comment]
Thanks @azu!

**Pull request merged**
